/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minicrm;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import minicrm.entity.Customer;
import minicrm.entity.Interaction;
import minicrm.entity.Representative;

/**
 *
 * @author Elmira
 */
public class MainWindow extends javax.swing.JFrame {

    Database db;
    DefaultListModel<Representative> modelRepresentativeList = new DefaultListModel<>();

    DefaultListModel<Customer> modelCustomerList = new DefaultListModel<>();
    DefaultListModel<Interaction> modelInteractionList = new DefaultListModel<>();
    String[] splitTo;

    public MainWindow() {

        try {
            db = new Database();
            initComponents();

            refreshRepList();
            refreshCustList();
            refreshInterList();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed to open database connection",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAddRep = new javax.swing.JDialog();
        lbldlgFistname = new javax.swing.JLabel();
        tfDlgFisrtName_Rep = new javax.swing.JTextField();
        lbldlgLastName = new javax.swing.JLabel();
        tfDlgLastName_Rep = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btndlgAddRep = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        dlgAddCustomer = new javax.swing.JDialog();
        lblDlgCustID = new javax.swing.JLabel();
        lblDlgFirstname = new javax.swing.JLabel();
        lblDlgelastname = new javax.swing.JLabel();
        lblDlgAddress = new javax.swing.JLabel();
        lblDlgpostalCode = new javax.swing.JLabel();
        lblDlgPhoneNo = new javax.swing.JLabel();
        lbldleSIN = new javax.swing.JLabel();
        tfDlgCusID = new javax.swing.JTextField();
        tfDlgFisrtnameCust = new javax.swing.JTextField();
        tfDlglastnameCust = new javax.swing.JTextField();
        tfDlgAddressCust = new javax.swing.JTextField();
        tfDlgpostalCodeCust = new javax.swing.JTextField();
        tfDlgPhoneCust = new javax.swing.JTextField();
        tfDlgSIN = new javax.swing.JTextField();
        btnAddCust = new javax.swing.JButton();
        btnCancelCust = new javax.swing.JButton();
        dlg_Interaction_Cust_Rep = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        lbl_dlgInteraction_CurrentRep = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_dlginteraction_CurrentCust = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listInteractions = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_dlg_get_RepName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_interaction_date = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tfNotes = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tfAddnewInteraction = new javax.swing.JTextArea();
        btnAddNewInterAction = new javax.swing.JButton();
        lblCurrentRep = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRepresentative = new javax.swing.JList<>();
        lblFindCustomer = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCustomer = new javax.swing.JList<>();
        btnAddRep = new javax.swing.JButton();
        btnAddCustomer = new javax.swing.JButton();
        btnInteraction_Cust_Rep = new javax.swing.JButton();

        dlgAddRep.setModal(true);

        lbldlgFistname.setText("Fisrt name");

        lbldlgLastName.setText("Last Name");

        tfDlgLastName_Rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDlgLastName_RepActionPerformed(evt);
            }
        });

        jLabel3.setText("please enter the Representative name:");

        btndlgAddRep.setText("Add ");
        btndlgAddRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndlgAddRepActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgAddRepLayout = new javax.swing.GroupLayout(dlgAddRep.getContentPane());
        dlgAddRep.getContentPane().setLayout(dlgAddRepLayout);
        dlgAddRepLayout.setHorizontalGroup(
            dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddRepLayout.createSequentialGroup()
                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddRepLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgAddRepLayout.createSequentialGroup()
                                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldlgFistname)
                                    .addComponent(lbldlgLastName))
                                .addGap(30, 30, 30)
                                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfDlgFisrtName_Rep, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(tfDlgLastName_Rep)))
                            .addComponent(jLabel3)))
                    .addGroup(dlgAddRepLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btndlgAddRep)
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgAddRepLayout.setVerticalGroup(
            dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddRepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldlgFistname)
                    .addComponent(tfDlgFisrtName_Rep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldlgLastName)
                    .addComponent(tfDlgLastName_Rep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndlgAddRep)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgAddCustomer.setModal(true);

        lblDlgCustID.setText("customerID");

        lblDlgFirstname.setText("First name");

        lblDlgelastname.setText("last name");

        lblDlgAddress.setText("Address");

        lblDlgpostalCode.setText("postal Code");

        lblDlgPhoneNo.setText("Phone Number");

        lbldleSIN.setText("SIN");

        tfDlglastnameCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDlglastnameCustActionPerformed(evt);
            }
        });

        btnAddCust.setText("Add");
        btnAddCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustActionPerformed(evt);
            }
        });

        btnCancelCust.setText("cancel");

        javax.swing.GroupLayout dlgAddCustomerLayout = new javax.swing.GroupLayout(dlgAddCustomer.getContentPane());
        dlgAddCustomer.getContentPane().setLayout(dlgAddCustomerLayout);
        dlgAddCustomerLayout.setHorizontalGroup(
            dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                                .addComponent(lblDlgCustID)
                                .addGap(38, 38, 38)
                                .addComponent(tfDlgCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                                .addComponent(lblDlgFirstname)
                                .addGap(43, 43, 43)
                                .addComponent(tfDlgFisrtnameCust))
                            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                                .addComponent(lblDlgelastname)
                                .addGap(47, 47, 47)
                                .addComponent(tfDlglastnameCust))
                            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                                .addComponent(lblDlgAddress)
                                .addGap(54, 54, 54)
                                .addComponent(tfDlgAddressCust))
                            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                                .addComponent(lblDlgpostalCode)
                                .addGap(36, 36, 36)
                                .addComponent(tfDlgpostalCodeCust))
                            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDlgPhoneNo)
                                    .addComponent(lbldleSIN))
                                .addGap(23, 23, 23)
                                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDlgPhoneCust)
                                    .addComponent(tfDlgSIN)))))
                    .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnAddCust)
                        .addGap(75, 75, 75)
                        .addComponent(btnCancelCust)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        dlgAddCustomerLayout.setVerticalGroup(
            dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDlgCustID)
                    .addComponent(tfDlgCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDlgFirstname)
                    .addComponent(tfDlgFisrtnameCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDlgelastname)
                    .addComponent(tfDlglastnameCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDlgAddress)
                    .addComponent(tfDlgAddressCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDlgpostalCode)
                    .addComponent(tfDlgpostalCodeCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDlgPhoneNo)
                    .addComponent(tfDlgPhoneCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldleSIN)
                    .addComponent(tfDlgSIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelCust, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnAddCust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        dlg_Interaction_Cust_Rep.setModal(true);

        jLabel1.setText("Current representative:");

        lbl_dlgInteraction_CurrentRep.setText(".......");

        jLabel4.setText("Current Customer:");

        lbl_dlginteraction_CurrentCust.setText("...........");

        jLabel6.setText("list of interactions,sorted by date:");

        listInteractions.setModel(modelInteractionList);
        jScrollPane3.setViewportView(listInteractions);

        jLabel7.setText("Representative name:");

        lbl_dlg_get_RepName.setText("...........");

        jLabel9.setText("Interaction Date: ");

        lbl_interaction_date.setText("............");

        jLabel11.setText("notes:");

        tfNotes.setColumns(20);
        tfNotes.setRows(5);
        tfNotes.setEnabled(false);
        jScrollPane6.setViewportView(tfNotes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_dlg_get_RepName)
                            .addComponent(lbl_interaction_date))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_dlg_get_RepName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_interaction_date))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addContainerGap())
        );

        tfAddnewInteraction.setColumns(20);
        tfAddnewInteraction.setRows(5);
        jScrollPane5.setViewportView(tfAddnewInteraction);

        btnAddNewInterAction.setText("Add new interaction note");
        btnAddNewInterAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewInterActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnAddNewInterAction, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddNewInterAction)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlg_Interaction_Cust_RepLayout = new javax.swing.GroupLayout(dlg_Interaction_Cust_Rep.getContentPane());
        dlg_Interaction_Cust_Rep.getContentPane().setLayout(dlg_Interaction_Cust_RepLayout);
        dlg_Interaction_Cust_RepLayout.setHorizontalGroup(
            dlg_Interaction_Cust_RepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_Interaction_Cust_RepLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dlg_Interaction_Cust_RepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg_Interaction_Cust_RepLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_dlgInteraction_CurrentRep, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dlg_Interaction_Cust_RepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_Interaction_Cust_RepLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_dlginteraction_CurrentCust, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(dlg_Interaction_Cust_RepLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(dlg_Interaction_Cust_RepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlg_Interaction_Cust_RepLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(dlg_Interaction_Cust_RepLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        dlg_Interaction_Cust_RepLayout.setVerticalGroup(
            dlg_Interaction_Cust_RepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_Interaction_Cust_RepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg_Interaction_Cust_RepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_dlgInteraction_CurrentRep)
                    .addComponent(jLabel4)
                    .addComponent(lbl_dlginteraction_CurrentCust))
                .addGroup(dlg_Interaction_Cust_RepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg_Interaction_Cust_RepLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlg_Interaction_Cust_RepLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Selected interaction details");
        jPanel1.getAccessibleContext().setAccessibleDescription("");
        jPanel2.getAccessibleContext().setAccessibleName("Add new iinteraction code");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCurrentRep.setText("Current Rep");

        listRepresentative.setModel(modelRepresentativeList);
        jScrollPane1.setViewportView(listRepresentative);

        lblFindCustomer.setText("Find Customer");

        listCustomer.setModel(modelCustomerList);
        jScrollPane2.setViewportView(listCustomer);

        btnAddRep.setText("Add Rep");
        btnAddRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRepActionPerformed(evt);
            }
        });

        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnInteraction_Cust_Rep.setText("Customer Interaction Representative");
        btnInteraction_Cust_Rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteraction_Cust_RepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCurrentRep)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addComponent(btnAddRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFindCustomer)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInteraction_Cust_Rep, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentRep)
                    .addComponent(lblFindCustomer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRep)
                    .addComponent(btnAddCustomer))
                .addGap(80, 80, 80)
                .addComponent(btnInteraction_Cust_Rep, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDlgLastName_RepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDlgLastName_RepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDlgLastName_RepActionPerformed

    private void btnAddRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRepActionPerformed
        dlgAddRep.pack();
        dlgAddRep.setVisible(true);


    }//GEN-LAST:event_btnAddRepActionPerformed

    private void btndlgAddRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndlgAddRepActionPerformed
        String firstName = tfDlgFisrtName_Rep.getText();
        String lastName = tfDlgLastName_Rep.getText();
        try {
            db.addRep(firstName, lastName);
            refreshRepList();
            tfDlgFisrtName_Rep.setText("");
            tfDlgLastName_Rep.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btndlgAddRepActionPerformed

    private void refreshRepList() {
        try {
            ArrayList<Representative> repList = db.getAllReps();
            modelRepresentativeList.clear();
            for (Representative r : repList) {
                modelRepresentativeList.addElement(r);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void refreshCustList() {
        try {
            ArrayList<Customer> custList = db.getAllCusts();
            modelCustomerList.clear();
            for (Customer c : custList) {
                modelCustomerList.addElement(c);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void refreshInterList() {
        try {
            ArrayList<Interaction> interactionList = db.getAllInteractions();
            modelInteractionList.clear();
            for (Interaction i : interactionList) {
                modelInteractionList.addElement(i);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dlgAddRep.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        dlgAddCustomer.pack();
        dlgAddCustomer.setVisible(true);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void tfDlglastnameCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDlglastnameCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDlglastnameCustActionPerformed

    private void btnAddCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustActionPerformed
        //   int custID = Integer.parseInt(tfDlgCusID.getText());
        String firstName = tfDlgFisrtnameCust.getText();
        String lastName = tfDlglastnameCust.getText();
        String address = tfDlgAddressCust.getText();
        String postalCode = tfDlgpostalCodeCust.getText();
        String phoneNumber = tfDlgPhoneCust.getText();

        try {
            db.addCust(firstName, lastName, address, address, postalCode, phoneNumber);
            refreshCustList();
            dlgAddCustomer.setVisible(false);
            tfDlgFisrtnameCust.setText("");
            tfDlglastnameCust.setText("");
            tfDlgAddressCust.setText("");
            tfDlgpostalCodeCust.setText("");
            tfDlgPhoneCust.setText("");

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddCustActionPerformed

    private void btnInteraction_Cust_RepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteraction_Cust_RepActionPerformed

        if ((listRepresentative.isSelectionEmpty()) || (listCustomer.isSelectionEmpty())) {
            // btnInteraction_Cust_Rep.setEnabled(false);
            JOptionPane.showMessageDialog(this,
                    "you forgot to select ",
                    "Selection missing",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            //    btnInteraction_Cust_Rep.setEnabled(true);
            dlg_Interaction_Cust_Rep.pack();
            dlg_Interaction_Cust_Rep.setVisible(true);
            refreshInterList();

            String repname1 = listRepresentative.getSelectedValue().toString();
            lbl_dlgInteraction_CurrentRep.setText(repname1);

            String custName = listCustomer.getSelectedValue().toString();
            lbl_dlginteraction_CurrentCust.setText(custName);

        }
    }//GEN-LAST:event_btnInteraction_Cust_RepActionPerformed

    private void btnAddNewInterActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewInterActionActionPerformed
        String tf = tfAddnewInteraction.getText();
        try {
            db.addInteraction(SOMEBITS, WIDTH, tf, tf);
            refreshInterList();
            tfAddnewInteraction.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddNewInterActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCust;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddNewInterAction;
    private javax.swing.JButton btnAddRep;
    private javax.swing.JButton btnCancelCust;
    private javax.swing.JButton btnInteraction_Cust_Rep;
    private javax.swing.JButton btndlgAddRep;
    private javax.swing.JDialog dlgAddCustomer;
    private javax.swing.JDialog dlgAddRep;
    private javax.swing.JDialog dlg_Interaction_Cust_Rep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblCurrentRep;
    private javax.swing.JLabel lblDlgAddress;
    private javax.swing.JLabel lblDlgCustID;
    private javax.swing.JLabel lblDlgFirstname;
    private javax.swing.JLabel lblDlgPhoneNo;
    private javax.swing.JLabel lblDlgelastname;
    private javax.swing.JLabel lblDlgpostalCode;
    private javax.swing.JLabel lblFindCustomer;
    private javax.swing.JLabel lbl_dlgInteraction_CurrentRep;
    private javax.swing.JLabel lbl_dlg_get_RepName;
    private javax.swing.JLabel lbl_dlginteraction_CurrentCust;
    private javax.swing.JLabel lbl_interaction_date;
    private javax.swing.JLabel lbldleSIN;
    private javax.swing.JLabel lbldlgFistname;
    private javax.swing.JLabel lbldlgLastName;
    private javax.swing.JList<Customer> listCustomer;
    private javax.swing.JList<Interaction> listInteractions;
    private javax.swing.JList<Representative> listRepresentative;
    private javax.swing.JTextArea tfAddnewInteraction;
    private javax.swing.JTextField tfDlgAddressCust;
    private javax.swing.JTextField tfDlgCusID;
    private javax.swing.JTextField tfDlgFisrtName_Rep;
    private javax.swing.JTextField tfDlgFisrtnameCust;
    private javax.swing.JTextField tfDlgLastName_Rep;
    private javax.swing.JTextField tfDlgPhoneCust;
    private javax.swing.JTextField tfDlgSIN;
    private javax.swing.JTextField tfDlglastnameCust;
    private javax.swing.JTextField tfDlgpostalCodeCust;
    private javax.swing.JTextArea tfNotes;
    // End of variables declaration//GEN-END:variables
}
