
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ipd
 */
public class NewPeopleList extends javax.swing.JFrame {

    DefaultListModel<Person> modelPersonList = new DefaultListModel<>();

    /**
     * Creates new form NewPeopleList
     */
    public NewPeopleList() {
        initComponents();
        // center window
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        // hide error labels
        lblNameError.setVisible(false);
        lblAgeError.setVisible(false);
        lblPostcodeError.setVisible(false);
        //
        centerOnParent(dlgEditPerson, true);
    }

// Center on parent ( absolute true/false (exact center or 25% upper left) )
    final public void centerOnParent(final Window child, final boolean absolute) {
        child.pack();
        boolean useChildsOwner = child.getOwner() != null ? ((child.getOwner() instanceof JFrame) || (child.getOwner() instanceof JDialog)) : false;
        final Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        final Dimension parentSize = useChildsOwner ? child.getOwner().getSize() : screenSize;
        final Point parentLocationOnScreen = useChildsOwner ? child.getOwner().getLocationOnScreen() : new Point(0, 0);
        final Dimension childSize = child.getSize();
        childSize.width = Math.min(childSize.width, screenSize.width);
        childSize.height = Math.min(childSize.height, screenSize.height);
        child.setSize(childSize);
        int x;
        int y;
        if ((child.getOwner() != null) && child.getOwner().isShowing()) {
            x = (parentSize.width - childSize.width) / 2;
            y = (parentSize.height - childSize.height) / 2;
            x += parentLocationOnScreen.x;
            y += parentLocationOnScreen.y;
        } else {
            x = (screenSize.width - childSize.width) / 2;
            y = (screenSize.height - childSize.height) / 2;
        }
        if (!absolute) {
            x /= 2;
            y /= 2;
        }
        child.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        ppmiDeleteItem = new javax.swing.JMenuItem();
        dlgEditPerson = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        tfDlgName = new javax.swing.JTextField();
        lblDlgNameError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDlgAge = new javax.swing.JTextField();
        lblDlgAgeError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDlgPostalCode = new javax.swing.JTextField();
        lblDlgPostcodeError = new javax.swing.JLabel();
        btDlgSaveChanges = new javax.swing.JButton();
        btDlgCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPeople = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        tfPostalCode = new javax.swing.JTextField();
        btAddPerson = new javax.swing.JButton();
        lblNameError = new javax.swing.JLabel();
        lblAgeError = new javax.swing.JLabel();
        lblPostcodeError = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miFileOpen = new javax.swing.JMenuItem();
        miFileSaveAllAs = new javax.swing.JMenuItem();
        miFileSaveSelectedAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miFileExit = new javax.swing.JMenuItem();

        ppmiDeleteItem.setText("Delete item");
        ppmiDeleteItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ppmiDeleteItemMouseReleased(evt);
            }
        });
        popupMenu.add(ppmiDeleteItem);

        dlgEditPerson.setModal(true);

        jLabel4.setText("Name:");

        lblDlgNameError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDlgNameError.setForeground(new java.awt.Color(204, 0, 0));
        lblDlgNameError.setText("name must be 2-20 characters, no semicolons");

        jLabel5.setText("Age:");

        lblDlgAgeError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDlgAgeError.setForeground(new java.awt.Color(204, 0, 0));
        lblDlgAgeError.setText("age must be between 1 and 150");

        jLabel6.setText("Postal code:");

        lblDlgPostcodeError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDlgPostcodeError.setForeground(new java.awt.Color(204, 0, 0));
        lblDlgPostcodeError.setText("postal code must be valid A1A1A1 format");

        btDlgSaveChanges.setText("Save changes");
        btDlgSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDlgSaveChangesActionPerformed(evt);
            }
        });

        btDlgCancel.setText("Cancel");
        btDlgCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDlgCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgEditPersonLayout = new javax.swing.GroupLayout(dlgEditPerson.getContentPane());
        dlgEditPerson.getContentPane().setLayout(dlgEditPersonLayout);
        dlgEditPersonLayout.setHorizontalGroup(
            dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgEditPersonLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(66, 66, 66)
                        .addGroup(dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgEditPersonLayout.createSequentialGroup()
                                .addComponent(lblDlgNameError)
                                .addGap(0, 201, Short.MAX_VALUE))
                            .addComponent(tfDlgName)))
                    .addGroup(dlgEditPersonLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79)
                        .addGroup(dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgEditPersonLayout.createSequentialGroup()
                                .addComponent(lblDlgAgeError)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfDlgAge)))
                    .addGroup(dlgEditPersonLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addGroup(dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDlgPostalCode)
                            .addGroup(dlgEditPersonLayout.createSequentialGroup()
                                .addComponent(lblDlgPostcodeError)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(dlgEditPersonLayout.createSequentialGroup()
                                .addComponent(btDlgSaveChanges)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDlgCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)))))
                .addGap(32, 32, 32))
        );
        dlgEditPersonLayout.setVerticalGroup(
            dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDlgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDlgNameError)
                .addGap(27, 27, 27)
                .addGroup(dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDlgAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDlgAgeError)
                .addGap(38, 38, 38)
                .addGroup(dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDlgPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDlgPostcodeError)
                .addGap(27, 27, 27)
                .addGroup(dlgEditPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDlgSaveChanges)
                    .addComponent(btDlgCancel))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstPeople.setModel(modelPersonList);
        lstPeople.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPeopleMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstPeopleMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lstPeople);

        jLabel1.setText("Name:");

        jLabel2.setText("Postal code:");

        jLabel3.setText("Age:");

        btAddPerson.setText("Add person");
        btAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPersonActionPerformed(evt);
            }
        });

        lblNameError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(204, 0, 0));
        lblNameError.setText("name must be 2-20 characters, no semicolons");

        lblAgeError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAgeError.setForeground(new java.awt.Color(204, 0, 0));
        lblAgeError.setText("age must be between 1 and 150");

        lblPostcodeError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPostcodeError.setForeground(new java.awt.Color(204, 0, 0));
        lblPostcodeError.setText("postal code must be valid A1A1A1 format");

        jMenu1.setText("File");

        miFileOpen.setText("Open ...");
        jMenu1.add(miFileOpen);

        miFileSaveAllAs.setText("Save all as ...");
        jMenu1.add(miFileSaveAllAs);

        miFileSaveSelectedAs.setText("Save selected as ...");
        miFileSaveSelectedAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFileSaveSelectedAsActionPerformed(evt);
            }
        });
        jMenu1.add(miFileSaveSelectedAs);
        jMenu1.add(jSeparator1);

        miFileExit.setText("Exit");
        jMenu1.add(miFileExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAddPerson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNameError)
                                .addGap(0, 74, Short.MAX_VALUE))
                            .addComponent(tfName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAgeError)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfAge)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPostcodeError)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfPostalCode))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNameError)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAgeError)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPostcodeError)
                .addGap(28, 28, 28)
                .addComponent(btAddPerson)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miFileSaveSelectedAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFileSaveSelectedAsActionPerformed
        // TODO: show file chooser first
        int[] indexList = lstPeople.getSelectedIndices();
        for (int idx : indexList) {
            Person p = modelPersonList.get(idx);
            System.out.printf("Sel[%d]: %s\n", idx, p);
        }
    }//GEN-LAST:event_miFileSaveSelectedAsActionPerformed

    private boolean isPersonDataValid(String name, JLabel nameError,
            String ageStr, JLabel ageError, String postcode, JLabel postcodeError) {
        boolean isNameInvalid = (name.length() < 2 || name.length() > 20);
        lblNameError.setVisible(isNameInvalid);
        //
        int age = 0;
        boolean isAgeInvalid;
        try {
            age = Integer.parseInt(ageStr);
            isAgeInvalid = age < 1 || age > 150;
        } catch (NumberFormatException e) {
            isAgeInvalid = true;
        }
        lblAgeError.setVisible(isAgeInvalid);
        //
        boolean isPostcodeInvalid = !postcode.matches("[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]");
        lblPostcodeError.setVisible(isPostcodeInvalid);
        //
        return (!(isNameInvalid || isAgeInvalid || isPostcodeInvalid));
    }

    private void btAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPersonActionPerformed
        String name = tfName.getText();
        String ageStr = tfAge.getText();
        String postcode = tfPostalCode.getText().toUpperCase();
        //        
        if (isPersonDataValid(name, lblNameError, ageStr, lblAgeError, postcode, lblPostcodeError)) {
            modelPersonList.addElement(new Person(name, Integer.parseInt(ageStr), postcode));
        }
    }//GEN-LAST:event_btAddPersonActionPerformed

    private void lstPeopleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPeopleMouseReleased
        if ((evt.getButton() == MouseEvent.BUTTON3) && (evt.getClickCount() == 1)) {
            lstPeople.setSelectedIndex(lstPeople.locationToIndex(evt.getPoint()));
            if (lstPeople.getSelectedIndex() != -1) {
                popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_lstPeopleMouseReleased

    private void ppmiDeleteItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppmiDeleteItemMouseReleased
        int index = lstPeople.getSelectedIndex();
        Person p = modelPersonList.get(index);
        //Custom button text
        Object[] options = {"Delete", "Cancel"};
        int choice = JOptionPane.showOptionDialog(this,
                "Are you sure you want to delete item: \n" + p,
                "Confirm deletion",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);
        if (choice == 0) {
            modelPersonList.remove(index);
        }
    }//GEN-LAST:event_ppmiDeleteItemMouseReleased

    private void lstPeopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPeopleMouseClicked
        if ((evt.getButton() == MouseEvent.BUTTON1) && (evt.getClickCount() == 2)) {
            // left button, double-click
            lstPeople.setSelectedIndex(lstPeople.locationToIndex(evt.getPoint()));
            int index = lstPeople.getSelectedIndex();
            if (index != -1) {
                Person p = modelPersonList.get(index);
                // fill in data of Person double-clicked for editing
                tfDlgName.setText(p.name);
                tfDlgAge.setText(p.age + "");
                tfDlgPostalCode.setText(p.postcode);
                // hide errors
                lblDlgNameError.setVisible(false);
                lblDlgAgeError.setVisible(false);
                lblDlgPostcodeError.setVisible(false);
                // show dialog
                dlgEditPerson.setVisible(true);
            }
        }
    }//GEN-LAST:event_lstPeopleMouseClicked

    private void btDlgCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDlgCancelActionPerformed
        dlgEditPerson.setVisible(false);
    }//GEN-LAST:event_btDlgCancelActionPerformed

    private void btDlgSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDlgSaveChangesActionPerformed
        String name = tfDlgName.getText();
        String ageStr = tfDlgAge.getText();
        String postcode = tfDlgPostalCode.getText();
        if (isPersonDataValid(name, lblDlgNameError, ageStr, lblDlgAgeError,
                postcode, lblDlgPostcodeError)) {
            Person p = modelPersonList.get(lstPeople.getSelectedIndex());
            // save changes
            p.name = name;
            p.age = Integer.parseInt(ageStr);
            p.postcode = postcode;
            //
            dlgEditPerson.setVisible(false);
        }
    }//GEN-LAST:event_btDlgSaveChangesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPeopleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPeopleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPeopleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPeopleList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPeopleList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddPerson;
    private javax.swing.JButton btDlgCancel;
    private javax.swing.JButton btDlgSaveChanges;
    private javax.swing.JDialog dlgEditPerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblAgeError;
    private javax.swing.JLabel lblDlgAgeError;
    private javax.swing.JLabel lblDlgNameError;
    private javax.swing.JLabel lblDlgPostcodeError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPostcodeError;
    private javax.swing.JList<Person> lstPeople;
    private javax.swing.JMenuItem miFileExit;
    private javax.swing.JMenuItem miFileOpen;
    private javax.swing.JMenuItem miFileSaveAllAs;
    private javax.swing.JMenuItem miFileSaveSelectedAs;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem ppmiDeleteItem;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfDlgAge;
    private javax.swing.JTextField tfDlgName;
    private javax.swing.JTextField tfDlgPostalCode;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPostalCode;
    // End of variables declaration//GEN-END:variables
}
