
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Elmira
 */
public class Quiz2Travel extends javax.swing.JFrame {

    DefaultListModel<Trip> modelTravelList = new DefaultListModel<>();
    File currentFile;

    /**
     * Creates new form Quiz2Travel
     */
    public Quiz2Travel() {
        initComponents();
        lblDlgNameError.setVisible(false);
        lblDlgDepartDateError.setVisible(false);
        lblDlgDestinationError.setVisible(false);
        lblDlgPassportNoError.setVisible(false);
        lblDlgReturnDateError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgTripList = new javax.swing.JDialog();
        lbldlgDestination = new javax.swing.JLabel();
        lblDlgName = new javax.swing.JLabel();
        lblDlgPasportNum = new javax.swing.JLabel();
        lblDlgDepartDate = new javax.swing.JLabel();
        lblDlgReturnDate = new javax.swing.JLabel();
        tfDlgDestination = new javax.swing.JTextField();
        tfDlgName = new javax.swing.JTextField();
        tfDlgPassportNo = new javax.swing.JTextField();
        tfDepartDate = new javax.swing.JTextField();
        tfReturnDate = new javax.swing.JTextField();
        lblDlgDestinationError = new javax.swing.JLabel();
        lblDlgNameError = new javax.swing.JLabel();
        lblDlgPassportNoError = new javax.swing.JLabel();
        lblDlgDepartDateError = new javax.swing.JLabel();
        lblDlgReturnDateError = new javax.swing.JLabel();
        btnDlgAddTripbtn = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();
        btnSaveSelected = new javax.swing.JButton();
        btnAddTrip = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTravel = new javax.swing.JList<>();

        dlgTripList.setModal(true);

        lbldlgDestination.setText("Des");

        lblDlgName.setText("Name");

        lblDlgPasportNum.setText("Passport no");

        lblDlgDepartDate.setText("Depart Date");

        lblDlgReturnDate.setText("Return Date");

        lblDlgDestinationError.setForeground(new java.awt.Color(255, 0, 51));
        lblDlgDestinationError.setText("2 to 29 char");

        lblDlgNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblDlgNameError.setText("2 to 29 char");

        lblDlgPassportNoError.setForeground(new java.awt.Color(255, 51, 51));
        lblDlgPassportNoError.setText("AA123456");

        lblDlgDepartDateError.setForeground(new java.awt.Color(255, 51, 51));
        lblDlgDepartDateError.setText("yyyy/mm/dd");

        lblDlgReturnDateError.setForeground(new java.awt.Color(204, 51, 0));
        lblDlgReturnDateError.setText("yyyy/mm/dd");

        btnDlgAddTripbtn.setText("Add Trip");
        btnDlgAddTripbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgAddTripbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgTripListLayout = new javax.swing.GroupLayout(dlgTripList.getContentPane());
        dlgTripList.getContentPane().setLayout(dlgTripListLayout);
        dlgTripListLayout.setHorizontalGroup(
            dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTripListLayout.createSequentialGroup()
                .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgTripListLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dlgTripListLayout.createSequentialGroup()
                                .addComponent(lblDlgName)
                                .addGap(60, 60, 60)
                                .addComponent(tfDlgName))
                            .addGroup(dlgTripListLayout.createSequentialGroup()
                                .addComponent(lbldlgDestination)
                                .addGap(69, 69, 69)
                                .addComponent(tfDlgDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDlgNameError)
                                .addGroup(dlgTripListLayout.createSequentialGroup()
                                    .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDlgPasportNum)
                                        .addComponent(lblDlgDepartDate)
                                        .addComponent(lblDlgReturnDate))
                                    .addGap(52, 52, 52)
                                    .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfDlgPassportNo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfDepartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(tfReturnDate)))
                                .addComponent(btnDlgAddTripbtn))))
                    .addGroup(dlgTripListLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lblDlgDestinationError))
                    .addGroup(dlgTripListLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblDlgPassportNoError))
                    .addGroup(dlgTripListLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblDlgDepartDateError))
                    .addGroup(dlgTripListLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblDlgReturnDateError)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        dlgTripListLayout.setVerticalGroup(
            dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTripListLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldlgDestination)
                    .addComponent(tfDlgDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDlgDestinationError)
                .addGap(25, 25, 25)
                .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDlgName)
                    .addComponent(tfDlgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lblDlgNameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDlgPasportNum)
                    .addComponent(tfDlgPassportNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDlgPassportNoError)
                .addGap(27, 27, 27)
                .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDlgDepartDate)
                    .addComponent(tfDepartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDlgDepartDateError)
                .addGap(33, 33, 33)
                .addGroup(dlgTripListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDlgReturnDate)
                    .addComponent(tfReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDlgReturnDateError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnDlgAddTripbtn)
                .addGap(19, 19, 19))
        );

        FileNameExtensionFilter ff = new FileNameExtensionFilter("SavedFfile (*.savedtxt)", "saved.txt");
        fileChooser.addChoosableFileFilter(ff);
        fileChooser.setFileFilter(ff);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSaveSelected.setText("SaveSelected");
        btnSaveSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSelectedActionPerformed(evt);
            }
        });

        btnAddTrip.setText("Add Trip");
        btnAddTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTripActionPerformed(evt);
            }
        });

        lstTravel.setModel(modelTravelList);
        jScrollPane1.setViewportView(lstTravel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnSaveSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTrip)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTrip)
                    .addComponent(btnSaveSelected))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTripActionPerformed

        dlgTripList.pack();
        dlgTripList.setVisible(true);


    }//GEN-LAST:event_btnAddTripActionPerformed
    private boolean isTravelDataValid(String destination, JLabel destinationError,
            String name, JLabel NameError, String passportNo, JLabel passportNoError, String departureStr, JLabel departureStrError,
            String returnDate, JLabel returnDateError) {
        boolean isDestinationInvalid = (destination.length() < 2 || destination.length() > 29);
        lblDlgDestinationError.setVisible(isDestinationInvalid);

        boolean isNameInvalid = (name.length() < 2 || name.length() > 29);
        lblDlgNameError.setVisible(isNameInvalid);

        boolean isPassportNoInvalid = !passportNo.matches("[A-Z][1-9]{8}");
        lblDlgPassportNoError.setVisible(isPassportNoInvalid);

        boolean isDepartureInvalid = !departureStr.matches("[1-9]{4}/[1-9]/[1-9]");
        lblDlgDepartDateError.setVisible(isDepartureInvalid);
        boolean isReturnInvalid = !returnDate.matches("[1-9]{4}/[1-9]/[1-9]") && (!returnDate.equals(departureStr)); //|| returnDate>departureStr));
        lblDlgReturnDate.setVisible(isReturnInvalid);
        return (!(isNameInvalid || isPassportNoInvalid || isDestinationInvalid));
    }


    private void btnDlgAddTripbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgAddTripbtnActionPerformed

        String dest = tfDlgDestination.getText();
        String name = tfDlgName.getText();
        String passportNo = tfDlgPassportNo.getText().toUpperCase();
        String departureStr = tfDepartDate.getText();
        String returnStr = tfReturnDate.getText();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
        
        try {
            modelTravelList.addElement(new Trip(dest, name, passportNo, formatter.parse(departureStr), formatter.parse(returnStr)));
            dlgTripList.dispose();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Unable to parse contents " + currentFile.getAbsolutePath(),
                    "File parse error",
                    JOptionPane.WARNING_MESSAGE
            );

        }

        /*  tfDlgName.setText(t.travellerName);
        tfDlgDestination.setText(t.destination);
        tfDlgPassportNo.setText(t.travellerPassportNo);
        tfDepartDate.setText(t.departureDate + "");
        tfReturnDate.setText(t.returnDate + "");*/
        lblDlgNameError.setVisible(false);
        lblDlgDepartDateError.setVisible(false);
        lblDlgDestinationError.setVisible(false);
        lblDlgPassportNoError.setVisible(false);
        lblDlgReturnDateError.setVisible(false);


    }//GEN-LAST:event_btnDlgAddTripbtnActionPerformed

    private void btnSaveSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSelectedActionPerformed

        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            currentFile = fileChooser.getSelectedFile();

            if (!currentFile.getName().toLowerCase().endsWith(".txt")) {
                currentFile = new File(currentFile.getAbsolutePath() + ".txt");
            }
            try (PrintWriter pw = new PrintWriter(currentFile)) {
                int[] indexList = lstTravel.getSelectedIndices();
                for (int idx : indexList) {
                    Trip t = modelTravelList.get(idx);
                    t = modelTravelList.getElementAt(idx);
                    pw.write(t.travellerName + ";" + t.travellerPassportNo + ";" + t.destination + ";" + t.departureDate + "\n");

                }
                pw.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Unable to write file contents to" + currentFile.getAbsolutePath(),
                        "File Acces error",
                        JOptionPane.WARNING_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnSaveSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz2Travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz2Travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz2Travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz2Travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz2Travel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTrip;
    private javax.swing.JButton btnDlgAddTripbtn;
    private javax.swing.JButton btnSaveSelected;
    private javax.swing.JDialog dlgTripList;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDlgDepartDate;
    private javax.swing.JLabel lblDlgDepartDateError;
    private javax.swing.JLabel lblDlgDestinationError;
    private javax.swing.JLabel lblDlgName;
    private javax.swing.JLabel lblDlgNameError;
    private javax.swing.JLabel lblDlgPasportNum;
    private javax.swing.JLabel lblDlgPassportNoError;
    private javax.swing.JLabel lblDlgReturnDate;
    private javax.swing.JLabel lblDlgReturnDateError;
    private javax.swing.JLabel lbldlgDestination;
    private javax.swing.JList<Trip> lstTravel;
    private javax.swing.JTextField tfDepartDate;
    private javax.swing.JTextField tfDlgDestination;
    private javax.swing.JTextField tfDlgName;
    private javax.swing.JTextField tfDlgPassportNo;
    private javax.swing.JTextField tfReturnDate;
    // End of variables declaration//GEN-END:variables
}
